### ISSUE TITLE
$HOME/.config/openbox/menu.xml does not exist

### ISSUE THREAD

**Issue by dariusity** [jruss06/boxmenu#2]
Can't get your script to work man, keep getting that menu.xml not existing in the mentioned directory which it obviously is there.

Location of boxmenu dir: ~/.config/boxmenu/
Boxmenu executable script: ~/.local/bin/boxmenu
Openbox default menu.xml: ~/.config/openbox/menu.xml

**Comment by jruss06** [comment]
I assume you are trying to use the --write option.

Are the permissions on ~/.config/openbox/menu.xml correct for your user?
Also you can just copy menu.xml from this repo directly to your ~/.config/openbox/menu.xml
